/**
 * Api.Issuing
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ConnectionRequestStatus = 'Shared' | 'Accepted' | 'Rejected' | 'Active';

export const ConnectionRequestStatus = {
    Shared: 'Shared' as ConnectionRequestStatus,
    Accepted: 'Accepted' as ConnectionRequestStatus,
    Rejected: 'Rejected' as ConnectionRequestStatus,
    Active: 'Active' as ConnectionRequestStatus
};