/**
 * Api.Issuing
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConnectionRequestStatus } from './connectionRequestStatus';
import { StaffMember } from './staffMember';

export interface ConnectionRequest { 
    id?: number;
    messageId?: string;
    receivedAt?: Date;
    status?: ConnectionRequestStatus;
    portalUserId?: string;
    displayName?: string;
    busMessage?: string;
    staffMemberId?: number;
    staffMember?: StaffMember;
}