/**
 * Api.Issuing
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type CredentialStatus = 'Active' | 'NeedInformation';

export const CredentialStatus = {
    Active: 'Active' as CredentialStatus,
    NeedInformation: 'NeedInformation' as CredentialStatus
};