/**
 * Api.Issuing
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Credential } from './credential';
import { StaffMember } from './staffMember';

export interface Presentation { 
    id?: number;
    staffMemberId?: number;
    staffMember?: StaffMember;
    credentials?: Array<Credential>;
}