/**
 * Api.Issuing
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConnectionRequest } from './connectionRequest';
import { Credential } from './credential';
import { Presentation } from './presentation';

export interface StaffMember { 
    id?: number;
    firstName: string;
    lastName: string;
    email?: string;
    dateOfBirth: Date;
    connectionRequests?: Array<ConnectionRequest>;
    credentials?: Array<Credential>;
    presentations?: Array<Presentation>;
}