/**
 * Api.IssuableCredentials
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MessageType } from './messageType';

export interface IssuableRequest { 
    id?: string;
    organisationCode?: string;
    userId?: string;
    sentAt?: Date;
    portalUserId?: string;
    messageType?: MessageType;
    message?: string;
    emailAddress?: string;
    useEmailAddress?: boolean;
    phoneNumber?: string;
    usePhoneNumber?: boolean;
}