/**
 * BFF.HrPortal
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface NhsidNrbacRoles { 
    personOrgid?: string;
    personRoleid?: string;
    orgCode?: string;
    roleName?: string;
    roleCode?: string;
    activities?: Array<string>;
    activityCodes?: Array<string>;
    workgroups?: Array<string>;
    workgroupsCodes?: Array<string>;
    aow?: Array<string>;
    aowCodes?: Array<string>;
}